/*
 * This file is generated by jOOQ.
 */
package org.skillup.infrastructure.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.skillup.infrastructure.jooq.tables.Order;
import org.skillup.infrastructure.jooq.tables.Promotion;
import org.skillup.infrastructure.jooq.tables.User;
import org.skillup.infrastructure.jooq.tables.records.OrderRecord;
import org.skillup.infrastructure.jooq.tables.records.PromotionRecord;
import org.skillup.infrastructure.jooq.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * skillup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = Internal.createUniqueKey(Order.ORDER, DSL.name("KEY_order_PRIMARY"), new TableField[] { Order.ORDER.ORDER_NUMBER }, true);
    public static final UniqueKey<PromotionRecord> KEY_PROMOTION_PRIMARY = Internal.createUniqueKey(Promotion.PROMOTION, DSL.name("KEY_promotion_PRIMARY"), new TableField[] { Promotion.PROMOTION.PROMOTION_ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.USER_ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_USERNAME = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_username"), new TableField[] { User.USER.USERNAME }, true);
}
