/*
 * This file is generated by jOOQ.
 */
package org.skillup.infrastructure.jooq;


import org.skillup.infrastructure.jooq.tables.User;


/**
 * Convenience access to all tables in skillup.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>skillup.user</code>.
     */
    public static final User USER = User.USER;
}
